spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: webadm
    password: '{cipher}3f106d35e43cd0ee5077032d4766f3623212c18d1b3a99c1439bae71216aa64c'
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://G:\webHome\configyml
        git:
          uri: https://github.com/ssim-itaz/spring_cloud_config_test
#          uri: file://G:\local_git          
# private인 경우 사용자 정보 및 비밀번호 사용          
#          username: ssim-itaz
