spring:
  datasource:
    url: jdbc:mariadb://211.236.48.204:3306/itz_lxp
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: '{cipher}a0fa1719238ed5460029f026876ea5fa02b1a25b3559044795fa15199a1c2eb8'
  rabbitmq:
    host: 211.236.48.234
    port: 5672
    username: webadm
    password: '{cipher}3f106d35e43cd0ee5077032d4766f3623212c18d1b3a99c1439bae71216aa64c'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ssim-itaz/spring_cloud_config_test
#          uri: file://G:\local_git          
# private인 경우 사용자 정보 및 비밀번호 사용          
#          username: ssim-itaz
#          password: password
